[standard_servers]
192.168.4.4  backup_method=rpi-clone backup_device=/dev/mmcblk0 load_threshold=4.0 docker_stacks='["docker/glances", "docker/immich-docker-compose", "docker/jellyfin", "docker/syncthing"]'
192.168.4.5  backup_method=rpi-clone backup_device=/dev/mmcblk0 load_threshold=4.0 docker_stacks='["docker/glances", "docker/immich-ml"]'
192.168.4.18 backup_method=none     backup_device=""            load_threshold=2.0 docker_stacks='["docker/glances"]' snap_packages='["vlc"]' vlc_stream_url="rtsp://192.168.4.19:8554/reolink_doorbell_sub"
192.168.4.19 backup_method=none     backup_device=""            load_threshold=4.0 docker_stacks='["docker/glances0", "docker/frigate0"]'

[readonly_servers]
192.168.4.11 backup_method=none     backup_device=""            load_threshold=4.0 overlay_readonly=true boot_readonly=true

[pikvm_servers]
192.168.4.66 backup_method=none     backup_device=""            load_threshold=4.0 ansible_user=root ansible_remote_tmp=/tmp/.ansible

[servers:children]
standard_servers
readonly_servers
pikvm_servers

[servers:vars]
ansible_user=shawn
ansible_python_interpreter=/usr/bin/python3
ansible_remote_tmp=/tmp/.ansible
