[servers]
192.168.4.4  backup_method=rpi-clone backup_device=/dev/mmcblk0 load_threshold=4.0 docker_stacks='["docker/glances", "docker/immich-docker-compose", "docker/jellyfin", "docker/syncthing"]'
192.168.4.5  backup_method=rpi-clone backup_device=/dev/mmcblk0 load_threshold=4.0 docker_stacks='["docker/glances", "docker/immich-ml"]'
192.168.4.18 backup_method=none     backup_device=""            load_threshold=2.0 docker_stacks='["docker/glances"]'
192.168.4.19 backup_method=none     backup_device=""            load_threshold=4.0 docker_stacks='["docker/glances0", "docker/frigate0"]'

[servers:vars]
ansible_user=shawn
ansible_python_interpreter=/usr/bin/python3
