services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      # Map Loki database to your hard drive
      - /srv/dev-disk-by-uuid-572f06f7-537c-4a40-8070-1952f73f65e2/remotelogs/loki-db:/loki
      # 2. MOUNT YOUR CONFIG FILE HERE (adjust './local-config.yaml' to your actual host path)
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /srv/dev-disk-by-uuid-572f06f7-537c-4a40-8070-1952f73f65e2/remotelogs/:/var/log/unifi/:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Map Grafana settings/dashboards to your hard drive
      - /srv/dev-disk-by-uuid-572f06f7-537c-4a40-8070-1952f73f65e2/remotelogs/grafana-db:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

